language: ruby
before_install:
  - gem install bundler
  - bundle --version
rvm:
  - 2.3.0
  - 2.4.1
  - 2.5.1
  - jruby-9.1.13.0
gemfile:
  - gemfiles/prawn-1.3.0.gemfile
  - gemfiles/prawn-2.1.0.gemfile
  - gemfiles/prawn-master.gemfile
