language: ruby
before_install:
  - gem install bundler
  - bundle --version
rvm:
  - 2.1.0-p0
  - 2.2.4
  - 2.3.0
  - jruby-9.0.5.0
  - rbx-3.19
gemfile:
  - gemfiles/prawn-1.3.0.gemfile
  - gemfiles/prawn-2.1.0.gemfile
  - gemfiles/prawn-master.gemfile
matrix:
  allow_failures:
    - rvm: rbx-3.19
